methods:
- model_cls: TabFlexModel
  model_hyperparameters:
    ag_args:
      name_suffix: _c1
    ag_args_ensemble:
      refit_folds: true
  name: TabFlex_c1_BAG_L1
  num_bag_folds: 8
  num_bag_sets: 1
  time_limit: 3600
  type: AGModelBagExperiment
